# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectFolder.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 642)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_rename = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rename.setGeometry(QtCore.QRect(150, 220, 300, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.btn_rename.setFont(font)
        self.btn_rename.setIconSize(QtCore.QSize(30, 30))
        self.btn_rename.setObjectName("btn_rename")
        self.text_folder_path = QtWidgets.QLineEdit(self.centralwidget)
        self.text_folder_path.setEnabled(True)
        self.text_folder_path.setGeometry(QtCore.QRect(40, 40, 520, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.text_folder_path.setFont(font)
        self.text_folder_path.setText("")
        self.text_folder_path.setObjectName("text_folder_path")
        self.text_model = QtWidgets.QLineEdit(self.centralwidget)
        self.text_model.setGeometry(QtCore.QRect(40, 120, 520, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.text_model.setFont(font)
        self.text_model.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_model.setPlaceholderText("")
        self.text_model.setObjectName("text_model")
        self.checkBox_type = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_type.setGeometry(QtCore.QRect(40, 170, 211, 40))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.checkBox_type.setFont(font)
        self.checkBox_type.setObjectName("checkBox_type")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 461, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.text_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_log.setGeometry(QtCore.QRect(10, 310, 580, 281))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.text_log.setFont(font)
        self.text_log.setObjectName("text_log")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 381, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 285, 201, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.toolBar.setFont(font)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_keywords = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_keywords.setIcon(icon)
        self.action_keywords.setObjectName("action_keywords")
        self.action_clear_log = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_clear_log.setIcon(icon1)
        self.action_clear_log.setObjectName("action_clear_log")
        self.action_select_folder = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imgs/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_select_folder.setIcon(icon2)
        self.action_select_folder.setObjectName("action_select_folder")
        self.action_save_log = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imgs/save_log.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save_log.setIcon(icon3)
        self.action_save_log.setObjectName("action_save_log")
        self.toolBar.addAction(self.action_select_folder)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_keywords)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_clear_log)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_save_log)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " One-click modification V1.0"))
        self.btn_rename.setText(_translate("MainWindow", "Rename files"))
        self.checkBox_type.setText(_translate("MainWindow", " Include report type"))
        self.label.setText(_translate("MainWindow", "Click \'Select Folder\' to choose reports folder"))
        self.text_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'等线\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Type model number in blank below"))
        self.label_2.setText(_translate("MainWindow", "Log will print below"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_keywords.setText(_translate("MainWindow", "Add Keywords"))
        self.action_keywords.setToolTip(_translate("MainWindow", "Add Keywords"))
        self.action_clear_log.setText(_translate("MainWindow", "Clear Log"))
        self.action_clear_log.setToolTip(_translate("MainWindow", "Clear Log"))
        self.action_select_folder.setText(_translate("MainWindow", "Select Folder"))
        self.action_select_folder.setToolTip(_translate("MainWindow", "Select Folder"))
        self.action_save_log.setText(_translate("MainWindow", "Save Log"))
        self.action_save_log.setToolTip(_translate("MainWindow", "Save Log"))
